name: "bert_classifier"
platform: "onnxruntime_onnx"
max_batch_size: 8

input [
  {
    name: "input_ids"
    data_type: TYPE_INT32
    dims: [ -1 ]  # README의 Dynamic Sequence 설정 적용
  },
  {
    name: "attention_mask"
    data_type: TYPE_INT32
    dims: [ -1 ]
  }
]

output [
  {
    name: "output"
    data_type: TYPE_FP32
    dims: [ 2 ]   # [일치 확인] 분류 클래스 수 동기화
  }
]

dynamic_batching { max_queue_delay_microseconds: 100 }
